name: screen_shot
description: Take a screenshot for windows desktop
version: 0.0.1
homepage: https://github.com/m-mosalam1998/screenshot_windows

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: ScreenShotPlugin
